CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  role ENUM('LIBRARIAN','USER') NOT NULL DEFAULT 'USER',
  is_blacklisted BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categories (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE books (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  author VARCHAR(255) NOT NULL,
  genre VARCHAR(100),
  language VARCHAR(50),
  isbn VARCHAR(13) UNIQUE,
  status ENUM('AVAILABLE','RESERVED') DEFAULT 'AVAILABLE',
  image_url VARCHAR(512),
  category_id INT,
  CONSTRAINT fk_book_category FOREIGN KEY (category_id)
    REFERENCES categories(id) ON DELETE SET NULL
);

CREATE TABLE reservations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  book_id INT NOT NULL,
  reservation_date DATE NOT NULL,
  due_date DATE NOT NULL,
  status ENUM('ACTIVE','RETURNED') DEFAULT 'ACTIVE',
  CONSTRAINT fk_res_user FOREIGN KEY (user_id)
    REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_res_book FOREIGN KEY (book_id)
    REFERENCES books(id) ON DELETE CASCADE
);
